# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Written in code'
tagline:          'Written in code, sealed in ink'
description:      'Discover expert insights on engineering leadership, technology stacks, talent development, and learning cultures. Unlock strategies for success in the ever-evolving tech landscape'
url:              https://babafemio.com
baseurl:          /

author:
  name:           'Babafemi Ogungbamila'
  url:            https://babafemio.com
  twitter:        babafemio

#paginate:         5

pagination:
  enabled: true
  debug: false
  collections: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  
#Plugins
plugins: 
  - jekyll-paginate-v2
  - jekyll-seo-tag

# Other variables
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/babafemio/babafemio.github.io

# Social
social:
  name: Babafemi Ogungbamila
  links:
    - https://www.twitter.com/babafemio
    - https://www.instagram.com/babafemio
    - https://linkedin.com/in/babafemio


twitter:
  username: babafemio
  card: summary