# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Written in code'
tagline:          'Written in code, sealed in ink'
description:      'Written in code, sealed in ink'
url:              https://babafemio.com
baseurl:          /

author:
  name:           'Babafemi Ogungbamila'
  url:            https://twitter.com/babafemio

#paginate:         5

pagination:
  enabled: true
  debug: false
  collections: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  
#Plugins
plugins: [jekyll-paginate-v2]

# Other variables
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/babafemio/babafemio.github.io
